name: check
on:
  push:
    branches:
      - main
    pull_request:


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install Python dependencies
        run: pip install '.[dev]'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - run: pre-commit run --show-diff-on-failure --color=always --all-files
        shell: bash
